add main page
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #10
Opened 2022-03-27 15:24 UTC by Evgeny-Davydov

2022-03-27 15:32 UTC, Evgeny-Davydov commented on components/footer/footer.css
> +.footer__text_description {
В figma текст не растянут по всем футеру. Можно было сделать через паддинг. Но, может, в футере в будущем будет еще как-то текст слева или справа, и можно будет создать еще один класс-модификатор под него

2022-03-27 15:34 UTC, Evgeny-Davydov commented on components/footer/footer.css
> +.footer__text_description {
В figma текст не растянут по всем футеру. Можно было сделать через паддинг. Но, может, в футере в будущем будет еще как-то текст слева или справа, и можно будет создать еще один класс-модификатор под него

2022-03-28 10:28 UTC, GSemikozov requested changes

2022-03-28 10:28 UTC, GSemikozov commented on components/header/header.css
> +    margin-left: 160px;
это будет лишним - мы ведь контент размещаем внутри контейнера, который и будет центрировать этот контент

2022-03-28 10:28 UTC, GSemikozov commented on components/footer/footer.css
> +    padding: 72px;
достаточно сверху и снизу, по краям нет смысла, поскольку мы используем контейнер чтобы центрировать контент

2022-03-28 14:03 UTC, Evgeny-Davydov commented on components/header/header.css
> +    margin-left: 160px;
В figma заголовок в header не по центру. Ширина страницы в figma 1440px. Её я задал в .container. И там у заголовка ещё отступ слева 160px. Можно записать margin `0 0 0 160px;`, чтобы не переназначать margin. Или имеется ввиду, что надо задать ширину контейнера `1440px - 160px - 160px`, т.е. 1120px? На занятии ты задал ширину .container 1110px.

2022-03-28 14:05 UTC, Evgeny-Davydov commented on components/footer/footer.css
> +    padding: 72px;
Понял. Исправлю

2022-03-28 15:42 UTC, GSemikozov commented on components/header/header.css
> +    margin-left: 160px;
нет, в этом нет смысла - контейнер делает все что нам нужно в этом плане)
отступы должны быть одинаковыми, это ошибка в дизайне (там прям визуально видно что отсчет берется на 5px левее текста).

2022-03-28 16:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 14:47 UTC, GSemikozov approved these changes

2022-03-31 14:48 UTC, merged