add skeleton solution
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #12
Opened 2022-03-29 16:13 UTC by Evgeny-Davydov

2022-03-29 16:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-29 19:44 UTC, GSemikozov requested changes

2022-03-29 19:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__string_title-1 {
лучше дать более емкое имя классу, например .skeleton__string_small / .skeleton__string_large и тд

2022-03-29 19:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину лучше в процентах - поможет при сужении / расширении экрана

2022-03-29 19:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__icon"></div>
здесь .skeleton__icon + .skeleton__text лучше завернуть в общий враппер по типу skeleton__header / skeleton__top, и уже там выравнивать

2022-03-31 12:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 13:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-31 13:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-31 14:48 UTC, GSemikozov approved these changes

2022-03-31 14:48 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-03-31 14:49 UTC, merged