add cards
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #13
Opened 2022-04-02 18:11 UTC by Evgeny-Davydov

2022-04-02 18:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-02 18:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-02 18:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-03 19:21 UTC, GSemikozov requested changes

2022-04-03 19:21 UTC, GSemikozov commented on components/preview/preview.css
> +    height: 367px;
если используем флексы, это уже не надо

2022-04-03 19:21 UTC, GSemikozov commented on components/card/card.css
> +.card__graph {
это для чего?)

2022-04-04 18:41 UTC, GSemikozov requested changes

2022-04-04 18:41 UTC, GSemikozov commented on components/preview/preview.css
> +    justify-content: center;
это однозначно с точки зрения UX будет не оч хорошо, так что да, можно удалить свойство

2022-04-04 18:41 UTC, GSemikozov commented on components/preview/preview.css
> +    height: 367px;
если убрать - карточки по умолчанию будут одной высоты по самой высокой, так работает флекс из коробки (align-items: stretch)

https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

2022-04-04 18:41 UTC, GSemikozov commented on components/card/card.css
> +    box-shadow: 0 2px 4px rgba(33, 36, 41, 0.05);
если не переиспользуется - то нет

2022-04-04 18:41 UTC, GSemikozov commented on components/card/card.css
> +.card__graph {
а, это для встраивания в карточку... тут проще модификатор именно у блока .histogram (например .histogram_preview), так удобнее завязаться под один общий модификатор и уже через него при необходимости менять значения для дочерних элементов (а .histogram__graph это и есть дочерний элемент блока .histogram)

2022-04-04 18:41 UTC, GSemikozov commented on index.html
> +                                        <div class="histogram__graph card__graph">
ответил выше. И в дополнение - "залазить в кишки" одного блока из другого (менять его элементы) - это неправильно)

2022-04-04 19:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-05 15:00 UTC, GSemikozov approved these changes

2022-04-05 15:00 UTC, merged