add mobile version and icons
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #20
Opened 2022-04-10 17:58 UTC by Evgeny-Davydov

Добавил:

- Иконки
- Логотип
- Стрелочку в аккордеоне
- Мобильную версию главной страницы
- Мобильную версию страницы гистограммы

Поменял иконки в Тултипе и Модальном окне

2022-04-10 17:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-10 18:16 UTC, Evgeny-Davydov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
Здесь немного поменял. Размер изображения 200px, шире растягивать не стоит. И border-radius теперь универсальный

2022-04-10 18:16 UTC, Evgeny-Davydov commented on assets/images/sprites.svg
> +        <symbol id="home" viewBox="0 0 24 24">
Оставил у всех иконок свойство `viewBox="0 0 24 24"`. Без него у меня не получается нормально масштабировать иконки

2022-04-10 18:16 UTC, Evgeny-Davydov commented on components/footer/footer.css
> +    display: none;
В Figma у мобильной версии нет футера, поэтому я решил его скрыть

2022-04-10 18:16 UTC, Evgeny-Davydov commented on index.html
> +                                        <p class="histogram__link">
Нельзя внутри тэга `<a>` вкладывать еще один тэг `<a>`. Поэтому я здесь поменял на `<p>`. Я так понял, в будущем в карточках будут просто картинки

2022-04-10 18:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-11 12:20 UTC, GSemikozov requested changes

2022-04-11 12:20 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
но по дизайну - 102х102. Для 200 можно модификатор _large

2022-04-11 12:20 UTC, GSemikozov commented on components/container/container.css
> +.container_header {
это касается внутренней реализации хедера, не контейнера - блоки не должны ничего знать о внутреннем устройстве других блоков, им это не важно и менять элементы одного блока через другие неправильно

2022-04-11 12:20 UTC, GSemikozov commented on components/container/container.css
> +.container_header {
и ниже

2022-04-11 12:20 UTC, GSemikozov commented on components/footer/footer.css
> +        width: 58%;
на планшете будет плохо, лучше max-width: 640px

2022-04-11 12:20 UTC, GSemikozov commented on index.html
> +                                        <p class="histogram__link">
да, в будущем будут картинки. В решении задачи можно оставить <a>, а в карточке поменять на div (семантически нейтральный тег)

2022-04-12 07:16 UTC, Evgeny-Davydov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 50%;
Исправил. Модификатор делать не стал, т.к. и без него всё выглядит нормально, а в будущем будут картинки, и он будет не нужен

2022-04-12 07:26 UTC, Evgeny-Davydov commented on components/footer/footer.css
> +        width: 58%;
Исправил. Я просто скрыл футер для мобильной версии, т.к. в фигме его не было, и не видел, что с ним происходит при сжатии)

2022-04-12 07:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-13 10:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-13 14:27 UTC, merged