add burger-menu solution
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #26
Opened 2022-04-22 14:49 UTC by Evgeny-Davydov

2022-04-22 14:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-22 14:54 UTC, Evgeny-Davydov commented on 09-lection7/01-burger-menu/index.html
> +        <button id="burger-menu-open" class="burger-menu__button burger-menu__button_open">
У меня здесь получается, что кнопка меню находится снаружи блока меню. Так можно делать с точки зрения БЭМ?

2022-04-22 17:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-23 15:40 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <button id="burger-menu-open" class="burger-menu__button burger-menu__button_open">
да, конечно, триггером меню может быть вообще любой элемент и это не зависит от меню

2022-04-23 15:41 UTC, GSemikozov requested changes

2022-04-23 15:41 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    height: 100vh;
тут уже повторно не надо vh, можно 100% (поскольку - относительно высоты .burger-menu)

2022-04-24 08:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 21:00 UTC, GSemikozov approved these changes

2022-04-27 21:00 UTC, merged