add button solution
js-tasks-ru/htmlcss-20220317_evg-a-davydov pull request #8
Opened 2022-03-24 08:32 UTC by Evgeny-Davydov

2022-03-24 08:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 14:49 UTC, GSemikozov requested changes

2022-03-24 14:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
рекомендую добавлять pointer-events: none - так пользователь точно не сможет взаимодействовать с disabled кнопкой

2022-03-24 15:37 UTC, Evgeny-Davydov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
Понял. Не знал про это свойство

2022-03-24 15:52 UTC, Evgeny-Davydov reviewed
Добавил pointer-events: none в .button:disabled

2022-03-24 16:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 16:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-25 19:19 UTC, GSemikozov approved these changes

2022-03-25 19:19 UTC, merged